### ISSUE TITLE
提示错误 WARNING	swSignalfd_setup: signalfd has been created

### ISSUE THREAD

**Issue by phper08** [mix-php/swoolefor#1]
![图片](https://user-images.githubusercontent.com/13127645/61517434-d383d180-aa39-11e9-8c9d-54b7c50af38d.png)

**Comment by phper08** [comment]
PHP 7.3.5
Swoole 4.4.0
inotify 2.0.0
Mix 2.0.7
Swoolefor 1.0.2

**Comment by phper08** [comment]
我的命令是 php swoolefor.phar run -c "php /www/mix/bin/mix-httpd start -c /www/mix/applications/http/config/httpd.php"

**Comment by phper08** [comment]
另外，怎么关闭啊，我在文档里没找到，我把上述命令的start改成stop也不行

![图片](https://user-images.githubusercontent.com/13127645/61518240-ac2e0400-aa3b-11e9-8db3-f336643b564a.png)

**Comment by phper08** [comment]
使用stop可以关闭，关闭后按Ctrl+C才行

**Comment by onanying** [comment]
你把 swoolefor kill 就关了，那个警告不用理会
