### ISSUE TITLE
WSL环境下是不是不支持呀

### ISSUE THREAD

**Issue by jadechenlei** [mix-php/swoolefor#11]
![image](https://user-images.githubusercontent.com/6230232/65856279-c6695400-e393-11e9-99bf-46537884920c.png)

您好,  我在WSL(Windows Subsystem for Linux) 环境下能支持启动项目.  但是文件更改后, 没有重启

**Comment by onanying** [comment]
inotify 监控不了映射的共享文件夹

**Comment by onanying** [comment]
用 git hook 在本地文件目录修改文件

**Comment by onanying** [comment]
https://github.com/mix-php/swoolefor/issues/9#issuecomment-536478497

**Comment by onanying** [comment]
@jadechenlei 

SwooleFor v1.1.3 已经支持文件扫描的方式捕获代码更新：

下载 swoolofor 的最新版本：https://github.com/mix-php/swoolefor/releases/latest

```
php swoolefor.phar --exec="php app.php arg..." --no-inotify
```
