### ISSUE TITLE
Hyperf 热重启没有用

### ISSUE THREAD

**Issue by hrb981027** [mix-php/swoolefor#12]
分别在WSL和Deepin环境下，写了全路径，可以正常启动，但是无论怎么修改都不会触发重启，请问是什么原因呀？

**Comment by onanying** [comment]
这个原因 https://github.com/mix-php/swoolefor/issues/9#issuecomment-536478497

**Comment by hrb981027** [comment]
里面的内容都看过了，还是没有用的

**Comment by onanying** [comment]
@hrb981027 

SwooleFor v1.1.3 已经支持文件扫描的方式捕获代码更新：

下载 swoolofor 的最新版本：https://github.com/mix-php/swoolefor/releases/latest

```
php swoolefor.phar --exec="php app.php arg..." --no-inotify
```

**Comment by hrb981027** [comment]
@onanying 
加不加--watch 都试过，一样的效果
![截图](https://user-images.githubusercontent.com/33706787/66699329-83569b80-ed18-11e9-97c7-80cf7ab655e2.png)

**Comment by hrb981027** [comment]
命令测试过，没有问题，路径也是完整的

**Comment by onanying** [comment]
@hrb981027  我也是醉了，估计 Swoole 4.4.6 又返回那个坑了

https://github.com/mix-php/swoolefor/issues/9#issuecomment-527829309

sub process exit too fast, sleep 2 seconds：

Swoole 从 4.4.0 开始接受我的提议支持 hook proc_open 方法，但后面到 4.4.3 / 4.4.4 修改 wait 时出了问题，导致bug，4.4.5 已经修复该问题，凡是出现不停 sub process exit too fast, sleep 2 seconds 请升级 Swoole 到 >= 4.4.5，然后下载 swoolofor 的最新版本：https://github.com/mix-php/swoolefor/releases/latest

**Comment by hrb981027** [comment]
@onanying  意思我用4.4.5.应该就没问题了，是吗？

**Comment by onanying** [comment]
@hrb981027 Swoole 4.4.5 是我测试过的，我等下找 Swoole 他们让他们加一个单测，针对这个问题

**Comment by hrb981027** [comment]
@onanying  好的，感谢大佬

**Comment by onanying** [comment]
@hrb981027 

刚测试了 swoole 4.4.6 ，我这里是可以的哦

```
[root@localhost data]# php swoolefor.phar --exec="php /data/bin/mix.php http:start" --no-inotify
   _____                     __     ______          
  / ___/      ______  ____  / /__  / ____/___  _____
  \__ \ | /| / / __ \/ __ \/ / _ \/ /_  / __ \/ ___/
 ___/ / |/ |/ / /_/ / /_/ / /  __/ __/ / /_/ / /    
/____/|__/|__/\____/\____/_/\___/_/    \____/_/  Version: 1.1.3, Swoole: 4.4.6, Use: file scan

[info] 2019-10-12 18:08:47.493 <29180> [message] executor start, exec: [php /data/bin/mix.php http:start]
[info] 2019-10-12 18:08:47.495 <29180> [message] fork sub process, pid: 29181
[info] 2019-10-12 18:08:47.496 <29180> [message] monitor start
[info] 2019-10-12 18:08:47.496 <29180> [message] watch: /data
[info] 2019-10-12 18:08:47.496 <29180> [message] delay: 3s
[info] 2019-10-12 18:08:47.496 <29180> [message] ext: .php,.json
[2019-10-12 10:08:47 @29180.0]	WARNING	swSignalfd_setup: signalfd has been created
[info] 2019-10-12 18:08:56.703 <29180> [message] file scan: file or directory changes
[info] 2019-10-12 18:08:56.704 <29180> [message] signal to process, pid: 29181, signal: 15
[info] 2019-10-12 18:08:56.706 <29180> [message] sub process exit, pid: 29181, exitcode: 0, termsig: 0, stopsig: 0
[info] 2019-10-12 18:08:56.706 <29180> [message] executor start, exec: [php /data/bin/mix.php http:start]
[info] 2019-10-12 18:08:56.708 <29180> [message] fork sub process, pid: 29186
[info] 2019-10-12 18:09:14.703 <29180> [message] file scan: file or directory changes
[info] 2019-10-12 18:09:14.703 <29180> [message] signal to process, pid: 29186, signal: 15
[info] 2019-10-12 18:09:14.707 <29180> [message] sub process exit, pid: 29186, exitcode: 0, termsig: 0, stopsig: 0
[info] 2019-10-12 18:09:14.707 <29180> [message] executor start, exec: [php /data/bin/mix.php http:start]
[info] 2019-10-12 18:09:14.709 <29180> [message] fork sub process, pid: 29189

```

**Comment by hrb981027** [comment]
诶，没得救了，我这还是不行

**Comment by onanying** [comment]
@hrb981027  你把环境信息贴给我，我找 swoole 反馈

```
cat /etc/redhat-release
php -v 
php --ri swoole 
```

**Comment by hrb981027** [comment]
<pre>
hrb@hrb-Deepin /code/hyperf (learn ✘)✹✭ ᐅ cat /etc/issue
Deepin GNU/Linux 15.11 \n \l

hrb@hrb-Deepin /code/hyperf (learn ✘)✹✭ ᐅ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Deepin
Description:    Deepin 15.11
Release:        15.11
Codename:       stable
</pre>
<pre>
hrb@hrb-Deepin /code/hyperf (learn ✘)✹✭ ᐅ php -v
PHP 7.3.9 (cli) (built: Sep 20 2019 15:47:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
</pre>
<pre>
hrb@hrb-Deepin /code/hyperf (learn ✘)✹✭ ᐅ php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.6
Built => Sep 20 2019 16:10:40
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.0j  20 Nov 2018
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
</pre>

**Comment by onanying** [comment]
我写了一个单测 demo ，有时间执行一下，贴一下执行结果：

```
<?php

\Swoole\Coroutine::set([
    'hook_flags' => SWOOLE_HOOK_ALL,
]);

\Swoole\Coroutine\run(function () {
	
	go(function () {
		while(true){
			\Swoole\Timer::after(1000, function() {
				var_dump($GLOBALS['pid']);
				posix_kill($GLOBALS['pid'], SIGKILL);
			});
			// fork进程
			$descriptorspec = [
				0 => ["pipe", "r"], // 标准输入，子进程从此管道中读取数据
				1 => ["pipe", "w"], // 标准输出，子进程向此管道中写入数据
				2 => ["pipe", "w"], // 标准错误
			];
			var_dump('proc_open');
			$process        = proc_open("ping 127.0.0.1", $descriptorspec, $pipes);
			$status         = proc_get_status($process);
			$GLOBALS['pid'] = $status['pid'];
			// 等待进程终止
			do {
				stream_get_contents($pipes[2]);
				$status = proc_get_status($process);
			} while ($status['running']);
		}
	});
	
});
```

**Comment by hrb981027** [comment]
@onanying 不停的报错
<pre>
hrb@hrb-Deepin /code/hyperf (learn ✘)✹✭ ᐅ php swoolefor.phar -e "php /code/hyperf/test.php"  --no-inotify
   _____                     __     ______          
  / ___/      ______  ____  / /__  / ____/___  _____
  \__ \ | /| / / __ \/ __ \/ / _ \/ /_  / __ \/ ___/
 ___/ / |/ |/ / /_/ / /_/ / /  __/ __/ / /_/ / /    
/____/|__/|__/\____/\____/_/\___/_/    \____/_/  Version: 1.1.3, Swoole: 4.4.6, Use: file scan

[info] 2019-10-12 10:46:56.224 <10313> [message] executor start, exec: [php /code/hyperf/test.php]
[info] 2019-10-12 10:46:56.225 <10313> [message] fork sub process, pid: 10314
[info] 2019-10-12 10:46:56.225 <10313> [message] monitor start
[info] 2019-10-12 10:46:56.225 <10313> [message] watch: /code/hyperf
[info] 2019-10-12 10:46:56.225 <10313> [message] delay: 3s
[info] 2019-10-12 10:46:56.225 <10313> [message] ext: .php,.json
[2019-10-12 18:46:56 @10313.0]  WARNING swSignalfd_setup: signalfd has been created
[info] 2019-10-12 10:46:56.333 <10313> [message] sub process exit, pid: 10314, exitcode: 255, termsig: 0, stopsig: 0
[warning] 2019-10-12 10:46:56.333 <10313> [message] sub process exit too fast, sleep 2 seconds
[info] 2019-10-12 10:46:58.335 <10313> [message] executor start, exec: [php /code/hyperf/test.php]
[info] 2019-10-12 10:46:58.335 <10313> [message] fork sub process, pid: 10324
[info] 2019-10-12 10:46:58.353 <10313> [message] sub process exit, pid: 10324, exitcode: 255, termsig: 0, stopsig: 0
</pre>

**Comment by hrb981027** [comment]
<pre>
hrb@hrb-Deepin /code/hyperf (learn ✘)✹✭ ᐅ php /code/hyperf/test.php 
PHP Fatal error:  Uncaught Error: Call to undefined function go() in /code/hyperf/test.php:9
Stack trace:
#0 {main}
  thrown in /code/hyperf/test.php on line 9

Fatal error: Uncaught Error: Call to undefined function go() in /code/hyperf/test.php:9
Stack trace:
#0 {main}
  thrown in /code/hyperf/test.php on line 9
</pre>

**Comment by onanying** [comment]
@hrb981027 
 
用这个，你的关掉了短方法：

```
<?php

\Swoole\Coroutine::set([
    'hook_flags' => SWOOLE_HOOK_ALL,
]);

\Swoole\Coroutine\run(function () {
	
	\Swoole\Coroutine::create(function () {
		while(true){
			\Swoole\Timer::after(1000, function() {
				var_dump("kill {$GLOBALS['pid']}");
				posix_kill($GLOBALS['pid'], SIGKILL);
			});
			// fork进程
			$descriptorspec = [
				0 => ["pipe", "r"], // 标准输入，子进程从此管道中读取数据
				1 => ["pipe", "w"], // 标准输出，子进程向此管道中写入数据
				2 => ["pipe", "w"], // 标准错误
			];
			var_dump('proc_open');
			$process        = proc_open("ping 127.0.0.1", $descriptorspec, $pipes);
			$status         = proc_get_status($process);
			echo "第1次 ";
			var_dump($status['running']);
			$GLOBALS['pid'] = $status['pid'];
			// 等待进程终止
			do {
				stream_get_contents($pipes[2]);
				$status = proc_get_status($process);
				echo "第n次 ";
				var_dump($status['running']); // 问题：在某些Swoole版本，某些环境，因 proc_open 启动的命令立即被关闭了，导致这里是 false
			} while ($status['running']);
		}
	});
	
});
```

**Comment by hrb981027** [comment]
现在就是正在运行，但是没有啥动静
<pre>
hrb@hrb-Deepin /code/hyperf (learn ✘)✹✭ ᐅ php swoolefor.phar -e "php /code/hyperf/test.php"  --no-inotify
   _____                     __     ______          
  / ___/      ______  ____  / /__  / ____/___  _____
  \__ \ | /| / / __ \/ __ \/ / _ \/ /_  / __ \/ ___/
 ___/ / |/ |/ / /_/ / /_/ / /  __/ __/ / /_/ / /    
/____/|__/|__/\____/\____/_/\___/_/    \____/_/  Version: 1.1.3, Swoole: 4.4.6, Use: file scan

[info] 2019-10-12 11:15:14.994 <15674> [message] executor start, exec: [php /code/hyperf/test.php]
[info] 2019-10-12 11:15:14.994 <15674> [message] fork sub process, pid: 15675
[info] 2019-10-12 11:15:14.995 <15674> [message] monitor start
[info] 2019-10-12 11:15:14.995 <15674> [message] watch: /code/hyperf
[info] 2019-10-12 11:15:14.995 <15674> [message] delay: 3s
[info] 2019-10-12 11:15:14.995 <15674> [message] ext: .php,.json
[2019-10-12 19:15:15 @15674.0]  WARNING swSignalfd_setup: signalfd has been created



</pre>

**Comment by onanying** [comment]
@hrb981027 执行我上面贴的 demo 测试 https://github.com/mix-php/swoolefor/issues/12#issuecomment-541313509 ，这样我才能分析你的问题，然后找 swoole 反馈

**Comment by hrb981027** [comment]
@onanying 我执行了，就是上面那个运行test.php 的结果，没有任何动作

**Comment by onanying** [comment]
@hrb981027  你理解错了，不是要你用 swoolefor 去执行，是让你直接用 php 执行：

```
php /code/hyperf/test.php
```

**Comment by hrb981027** [comment]
@onanying 下面就没动静了，一直卡着
<pre>
hrb@hrb-Deepin /code/hyperf (learn ✘)✹✭ ᐅ php /code/hyperf/test.php     
string(9) "proc_open"
第1次 bool(true)
string(10) "kill 16511"

</pre>

**Comment by hrb981027** [comment]
卡好长时间，执行到这了
<pre>
hrb@hrb-Deepin /code/hyperf (learn ✘)✹✭ ᐅ php /code/hyperf/test.php     
string(9) "proc_open"
第1次 bool(true)
string(10) "kill 16511"
第n次 bool(false)
string(9) "proc_open"
第1次 bool(true)
string(10) "kill 16611"

</pre>

**Comment by hrb981027** [comment]
@onanying 我换了服务器运行了一下，输出的非常快，我现在怀疑是我电脑的问题了，不行就算了吧，感谢大佬了
<pre>
hrb@maikeos ~ ᐅ /usr/local/php7.3.9/bin/php /home/hrb/test.php                                                                                                                                                 [1/18]
string(9) "proc_open"                                                                                                                                                                                                
第1次 bool(true)
string(10) "kill 10271"
第n次 bool(true)
第n次 bool(true)
第n次 bool(true)
第n次 bool(true)
第n次 bool(true)
第n次 bool(false)
string(9) "proc_open"
第1次 bool(true)
string(10) "kill 10276"
第n次 bool(true)
第n次 bool(true)
第n次 bool(true)
第n次 bool(false)
string(9) "proc_open"
第1次 bool(true)
string(10) "kill 10277"
第n次 bool(true)
第n次 bool(true)
第n次 bool(true)
第n次 bool(true)
第n次 bool(false)
string(9) "proc_open"
第1次 bool(true)
string(10) "kill 10278"
第n次 bool(true)
第n次 bool(true)
第n次 bool(true)
第n次 bool(false)
string(9) "proc_open"
第1次 bool(true)
string(10) "kill 10279"
第n次 bool(true)
第n次 bool(true)
第n次 bool(true)
第n次 bool(false)
string(9) "proc_open"
第1次 bool(true)
string(10) "kill 10280"
第n次 bool(true)
第n次 bool(true)
第n次 bool(true)
第n次 bool(true)
第n次 bool(false)
string(9) "proc_open"
第1次 bool(true)
</pre>

**Comment by onanying** [comment]
@hrb981027  我给你总结一下

```
hrb@hrb-Deepin /code/hyperf (learn ✘)✹✭ ᐅ php /code/hyperf/test.php     
string(9) "proc_open"
第1次 bool(true)
string(10) "kill 16511"
第n次 bool(false)
string(9) "proc_open"
第1次 bool(true)
string(10) "kill 16611"
```

这一个测试是通过的，因为没有乱序，但你的问题是 kill 的时候太久，会卡，也就是说，你这台机器不更新的问题是发送信号的时候会卡那，导致不更新，Swoole 4.4.6 没有问题。

而你换了一台机，变的很快，然后是结果是乱序的，说明这台机应该是 Swoole 4.4.5 以下版本。

结论就是，Swoole >= 4.4.5 的 SwooleFor 是 ok 的，应该是你的个体机器的问题（kill 会卡）。

**Comment by hrb981027** [comment]
@onanying 应该是我个体机器的原因，刚刚快的那台也是4.4.6的版本，感谢大佬一路的帮助。

**Comment by hrb981027** [comment]
@onanying 发现了一个问题，我换了另一台Ubuntu系统，4.4.5的版本，也是没用。我之前用的WSL和Deepin都是Debian的，而我刚刚运行很快的那个是Centos系统，会不会是两大系统的原因？

**Comment by xc9788** [comment]
@onanying debian系列系统貌似都会慢。 #12 的示例中 stream_get_contents($pipes[2]); 的作用是什么？ 这个函数执行的时间如下
string(9) "proc_open"
第1次 bool(true)
start at 1571037028
Resource id #6
string(9) "kill 7588"
end at 1571037088
第n次 bool(false)
string(9) "proc_open"
第1次 bool(true)
start at 1571037089
Resource id #10
string(9) "kill 7609"
1571037028end at 1571037149
第n次 bool(false)
string(9) "proc_open"
第1次 bool(true)
start at 1571037150

...
这个函数貌似这个单测中没有作用，但却消耗了1分钟的执行时间，实在疑惑望大佬解答...

**Comment by onanying** [comment]
> @onanying 发现了一个问题，我换了另一台Ubuntu系统，4.4.5的版本，也是没用。我之前用的WSL和Deepin都是Debian的，而我刚刚运行很快的那个是Centos系统，会不会是两大系统的原因？

如果按你说的，那没有一种环境是能正确执行 SwooleFor 的，而我的 CentOS 测试是 ok 的

上面的单测，如果 1s 输出一下，顺序是有规则的，就是能正常使用的环境，乱序就是 Swoole 版本的问题，而卡应该下面那个原因

**Comment by onanying** [comment]
> @onanying debian系列系统貌似都会慢。 #12 的示例中 stream_get_contents($pipes[2]); 的作用是什么？ 这个函数执行的时间如下
> string(9) "proc_open"
> 第1次 bool(true)
> start at 1571037028
> Resource id #6
> string(9) "kill 7588"
> end at 1571037088
> 第n次 bool(false)
> string(9) "proc_open"
> 第1次 bool(true)
> start at 1571037089
> Resource id #10
> string(9) "kill 7609"
> 1571037028end at 1571037149
> 第n次 bool(false)
> string(9) "proc_open"
> 第1次 bool(true)
> start at 1571037150
> 
> ...
> 这个函数貌似这个单测中没有作用，但却消耗了1分钟的执行时间，实在疑惑望大佬解答...

@xc9788  你这样一说，可能就是 debian系列的 kill 后不会在进程管道中输出数据，看来我需要修改这一处的代码

**Comment by onanying** [comment]
@xc9788 @hrb981027 找到原因了，是因为 php 在 debian 系列，执行外部命令的时候和 redhat 系列不一样，debian 会多一步，会先 sh -c cmd，生成另一个子进程，而 proc_get_status 获取到的是 sh -c cmd  这个中转进程的id，导致进程获取错误。

我已经在 SwooleFor v1.1.4 增加代码修复这个问题，下载 v1.1.4 https://github.com/mix-php/swoolefor/releases/latest

**Comment by hrb981027** [comment]
@onanying  妥妥的，大佬稳。测试了，没问题了。
