### ISSUE TITLE
您好,适用phalcon 3.4.5+yar2.1 +swoole4.4吗?

### ISSUE THREAD

**Issue by feng99** [mix-php/swoolefor#16]
我并没有使用基于swoole的任何框架

项目的情况是这样的
Mvc框架用的phalcon3.4.5
想实现服务拆分
然后用了鸟哥的yar

yar默认是用http实现的rpc，感觉性能不给力，
又修改为swoole做tcp server

现在是phalcon 3.4.5+yar2.1 +swoole4.4

Swoole启动后，常驻内存，也遇到了代码修改后重启的问题，您这个适用我这个情况吗？谢谢回答。

**Comment by onanying** [comment]
@feng99  能用，原理就是文件修改就执行信号停止，然后重启

**Comment by feng99** [comment]
哇   真滴好
