### ISSUE TITLE
启动报错 Call to undefined function Mix\Core\go()

### ISSUE THREAD

**Issue by Niexiawei** [mix-php/swoolefor#2]
错误详情：[error] 2019-08-13 18:11:09 <42> [message] Call to undefined function Mix\Core\go() [0] Error in phar:///www/delivery/swoolefor.phar/vendor/mix/framework/src/Core/Coroutine.php line 101

PHP：7.2
SWOOLE：4.4.3
Swoolefor 1.0.2
inotify 2.0.0

启动命令 php swoolefor.phar run -c "php hyperf.php start" 

是我启动姿势不对吗

**Comment by onanying** [comment]
go() 是swoole提供的方法，当提示找不到这个方法时，就是当前php没有安装swoole，还有 `-c "php hyperf.php start"` 里面的命令执行的php文件必须要是绝对路径。

**Comment by Niexiawei** [comment]
![image](https://user-images.githubusercontent.com/29922984/62959987-49f2d400-be2c-11e9-99e0-77cfc29dd33d.png)
hyperf 可以正常启动
![image](https://user-images.githubusercontent.com/29922984/62960025-5f67fe00-be2c-11e9-97ef-3eafcd05dbdb.png)
绝对路径还是提示 找不到 go方法 
需要先安装mix框架吗

**Comment by onanying** [comment]
不需要，这个和mix没有任何关联，你把 `php -v` `php --ri swoole` 这两个版本信息给我看一下

**Comment by Niexiawei** [comment]
![image](https://user-images.githubusercontent.com/29922984/62990144-74b94880-be7d-11e9-96bf-91eca0f0e1f9.png)
![image](https://user-images.githubusercontent.com/29922984/62990170-8ac70900-be7d-11e9-83d4-d83d025c0612.png)

**Comment by onanying** [comment]
晕，swoole.use_shortname = Off 了，你在 php.ini 加一下 swoole.use_shortname = 1，后面我会升级 swoolefor 不使用短名了。

**Comment by Niexiawei** [comment]
ok  现在swoft 和 hyperf 都不支持 短名了
