### ISSUE TITLE
修改了业务代码不生效

### ISSUE THREAD

**Issue by dongmu101** [mix-php/swoolefor#3]
[warning] 2019-08-23 13:47:23.505 <18023> [message] opendir(//dev/fd/10/dev/fd/10/dev/fd/10/dev/fd/10/dev/fd/10/dev/fd/10/dev/fd/10/dev/fd/10/dev/fd/10/dev/fd/10/dev/fd/10/dev/fd/10/dev/fd/10/sys/kernel/debug/tracing): failed to open dir: Too many levels of symbolic links [2] Mix\Console\Exception\ErrorException in phar:///var/www/code/api.laravel/swoolefor.phar/src/Libraries/Monitor.php line 185

Version: 1.1.1, Swoole: 4.4.2
系统：ubuntu 18.04
php:7.3.8
用的框架是LaravelS

**Comment by onanying** [comment]
把你的启动 swoolefor 的全部命令贴出来，估计是你没有按以下规则：

`--exec 内部可以是任何命令，必须为绝对路径，必须为前台执行的常驻程序 (否则会导致不断fork进程)`

**Comment by dongmu101** [comment]
报错发现问题了是路径不对。
php swoolefor.phar --exec="php bin/laravels start" --watch=/var/www/code/api.laravel/app
不过我设置了正确的路径但好像运行正常了，在编辑了代码还是监听不到文件变更不会热更新，不知道是什么原因。
之前用fswatch 1.11.2版本监听会一直有文件在变动,swoole 一直在 reload。如果用最新 fswatch 1.14 版本就监听不到如何文件变动，大佬你知道这是为什么么 让人很烦恼

**Comment by onanying** [comment]
php swoolefor.phar --exec="php bin/laravels start" --watch=/var/www/code/api.laravel/app

这里 --exec="php bin/laravels start" 里的脚本路径，必须是绝对路径，比如：--exec="php /data/bin/laravels start"

**Comment by onanying** [comment]
mac 么？ 不支持inotify扩展的，搞不了，用 docker for mac

**Comment by dongmu101** [comment]
是ubuntu 18.04 版本系统

**Comment by fkwl** [comment]
```
Creating hp-app ... done
Attaching to hp-app
hp-app        | composer self-update
hp-app        | You are already using composer version 1.9.0 (stable channel).
hp-app        | composer install
hp-app        | Do not run Composer as root/super user! See https://getcomposer.org/root for details
hp-app        | Loading composer repositories with package information
hp-app        | Installing dependencies (including require-dev) from lock file
hp-app        | Nothing to install or update
hp-app        | Generating autoload files
hp-app        | ocramius/package-versions:  Generating version class...
hp-app        | ocramius/package-versions: ...done generating version class
hp-app        | php swoolefor.phar -e "php /opt/www/bin/hyperf.php di:init-proxy && php /opt/www/bin/hyperf.php start"
hp-app        |    _____                     __     ______          
hp-app        |   / ___/      ______  ____  / /__  / ____/___  _____
hp-app        |   \__ \ | /| / / __ \/ __ \/ / _ \/ /_  / __ \/ ___/
hp-app        |  ___/ / |/ |/ / /_/ / /_/ / /  __/ __/ / /_/ / /    
hp-app        | /____/|__/|__/\____/\____/_/\___/_/    \____/_/  Version: 1.1.2, Swoole: 4.4.5
hp-app        | 
hp-app        | [info] 2019-09-17 03:55:05.858 <26> [message] executor start, exec: [php /opt/www/bin/hyperf.php di:init-proxy && php /opt/www/bin/hyperf.php start]
hp-app        | [info] 2019-09-17 03:55:05.862 <26> [message] fork sub process, pid: 27
hp-app        | [info] 2019-09-17 03:55:05.889 <26> [message] monitor start
hp-app        | [info] 2019-09-17 03:55:05.889 <26> [message] watch: /opt/www
hp-app        | [info] 2019-09-17 03:55:05.889 <26> [message] delay: 3s
hp-app        | [info] 2019-09-17 03:55:05.889 <26> [message] ext: .php,.json
hp-app        | [2019-09-17 03:55:18 @26.0]     WARNING swSignalfd_setup: signalfd has been created
```


我用 apline ubuntu 都试过了，修改不重载

**Comment by fkwl** [comment]
@onanying

**Comment by onanying** [comment]
@kuange 这个程序很简单，就是基于php的inotify扩展，不重载的话应该是inotify没有捕获到文件的变化，之前有用户说是共享文件inotify是没有捕获到，ftp传的这种是有的，inotify有一定局限性，没有办法，你也要检测一下你的系统对inotify的支持情况。

**Comment by onanying** [comment]
@kuange @erDong01 

SwooleFor v1.1.3 已经支持文件扫描的方式捕获代码更新：

下载 swoolofor 的最新版本：https://github.com/mix-php/swoolefor/releases/latest

```
php swoolefor.phar --exec="php app.php arg..." --no-inotify
```
