### ISSUE TITLE
不断的 fock 进程

### ISSUE THREAD

**Issue by guanzhao** [mix-php/swoolefor#7]
php swoolefor.phar -e "php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start" --ext=php,env --watch=/mnt/hgfs/code/xym_cli/hyperf-skeleton/

[info] 2019-08-31 18:16:06.227 <20887> [message] executor start, exec: [php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start]
[info] 2019-08-31 18:16:06.259 <20887> [message] fork sub process, pid: 20888
[info] 2019-08-31 18:16:06.266 <20887> [message] monitor start
[info] 2019-08-31 18:16:06.266 <20887> [message] watch: /mnt/hgfs/code/xym_cli/hyperf-skeleton/
[info] 2019-08-31 18:16:06.266 <20887> [message] delay: 3s
[info] 2019-08-31 18:16:06.266 <20887> [message] ext: .php,.env
[2019-08-31 18:16:13 @20887.0]	WARNING	swSignalfd_setup: signalfd has been created
[info] 2019-08-31 18:16:31.879 <20887> [message] notify: file changes
[info] 2019-08-31 18:16:31.879 <20887> [message] signal to process, pid: 20888, signal: 15
[info] 2019-08-31 18:16:31.943 <20887> [message] sub process exit, pid: 20888, exitcode: 0, termsig: 0, stopsig: 0
[warning] 2019-08-31 18:16:31.943 <20887> [message] sub process exit too fast, sleep 2 seconds
[info] 2019-08-31 18:16:33.946 <20887> [message] executor start, exec: [php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start]
[info] 2019-08-31 18:16:33.947 <20887> [message] fork sub process, pid: 20927
[info] 2019-08-31 18:16:33.947 <20887> [message] sub process exit, pid: 20927, exitcode: -1, termsig: 11, stopsig: 0
[warning] 2019-08-31 18:16:33.947 <20887> [message] sub process exit too fast, sleep 2 seconds
[info] 2019-08-31 18:16:35.949 <20887> [message] executor start, exec: [php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start]
[info] 2019-08-31 18:16:35.951 <20887> [message] fork sub process, pid: 20928
[info] 2019-08-31 18:16:35.952 <20887> [message] sub process exit, pid: 20928, exitcode: -1, termsig: 11, stopsig: 0
[warning] 2019-08-31 18:16:35.952 <20887> [message] sub process exit too fast, sleep 2 seconds
[info] 2019-08-31 18:16:37.953 <20887> [message] executor start, exec: [php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start]
[info] 2019-08-31 18:16:37.955 <20887> [message] fork sub process, pid: 20931
[info] 2019-08-31 18:16:37.957 <20887> [message] sub process exit, pid: 20931, exitcode: -1, termsig: 11, stopsig: 0
[warning] 2019-08-31 18:16:37.957 <20887> [message] sub process exit too fast, sleep 2 seconds
[info] 2019-08-31 18:16:39.960 <20887> [message] executor start, exec: [php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start]
[info] 2019-08-31 18:16:39.962 <20887> [message] fork sub process, pid: 20932
[info] 2019-08-31 18:16:39.963 <20887> [message] sub process exit, pid: 20932, exitcode: -1, termsig: 11, stopsig: 0
[warning] 2019-08-31 18:16:39.963 <20887> [message] sub process exit too fast, sleep 2 seconds
[info] 2019-08-31 18:16:41.964 <20887> [message] executor start, exec: [php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start]
[info] 2019-08-31 18:16:41.966 <20887> [message] fork sub process, pid: 20933
[info] 2019-08-31 18:16:41.968 <20887> [message] sub process exit, pid: 20933, exitcode: -1, termsig: 11, stopsig: 0
[warning] 2019-08-31 18:16:41.968 <20887> [message] sub process exit too fast, sleep 2 seconds
[info] 2019-08-31 18:16:43.969 <20887> [message] executor start, exec: [php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start]
[info] 2019-08-31 18:16:43.970 <20887> [message] fork sub process, pid: 20934
[info] 2019-08-31 18:16:43.970 <20887> [message] sub process exit, pid: 20934, exitcode: -1, termsig: 11, stopsig: 0
[warning] 2019-08-31 18:16:43.970 <20887> [message] sub process exit too fast, sleep 2 seconds

**Comment by onanying** [comment]
在执行前，你自己先 `php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start` 执行一下，看有没有问题，没有问题了再用 swoolefor

**Comment by guanzhao** [comment]
php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start  是可以正常使用的

**Comment by guanzhao** [comment]
swoolefor 开启之后,可以正常跑, 检测到文件更新后就一直fock ， 使用的vm 跑的 linux ，做的文件共享.

**Comment by onanying** [comment]
一般 fock 就是 执行 php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start 这个命令的时候，这个命令立即就结束了，没有hold在那里，因为正常常驻程序是会一直在前台执行的，所以你这个因该也是 php /mnt/hgfs/code/xym_cli/hyperf-skeleton/bin/hyperf.php start 这个命令在执行的时候出了问题。

**Comment by guanzhao** [comment]
我执行时都是能正常运行的

**Comment by onanying** [comment]
你这个问题我复现不了，没办法了，非常奇怪第一次exec是成功，第二次的时候不行，我想不出来是啥原因。

**Comment by onanying** [comment]
@guanzhao  找到原因了，按我这个处理 https://github.com/mix-php/swoolefor/issues/9#issuecomment-527829309

**Comment by guanzhao** [comment]
现在更想完好了,使用虚拟机的时候通过本地修改共享文件夹中的代码,不能检测到.

**Comment by onanying** [comment]
> 现在更想完好了,使用虚拟机的时候通过本地修改共享文件夹中的代码,不能检测到.

共享文件夹这种应该是 ext-inotify 捕获不到文件变化，系统不支持的话是没有办法的，只能用本地文件那种了。

**Comment by guanzhao** [comment]
好的感谢~ 没有其他问题了

**Comment by onanying** [comment]
@guanzhao 

SwooleFor v1.1.3 已经支持文件扫描的方式捕获代码更新：

下载 swoolofor 的最新版本：https://github.com/mix-php/swoolefor/releases/latest

```
php swoolefor.phar --exec="php app.php arg..." --no-inotify
```
