### ISSUE TITLE
hyperf不行

### ISSUE THREAD

**Issue by Kline-x** [mix-php/swoolefor#8]
请问一下，这脚本是不支持hyperf的吗？

**Comment by onanying** [comment]
支持，都可以，一定又是没有用绝对路径的，你把你执行的全部完整的命令贴出来

**Comment by Kline-x** [comment]
> 支持，都可以，一定又是没有用绝对路径的，你把你执行的全部完整的命令贴出来

大佬，我发现了问题所在，是因为我是在docker里面用的，当我在宿主机改了文件之后，docker内的文件虽然也发生了改变，但是这个脚本并没有生效

**Comment by onanying** [comment]
可能宿主的文件变化，在容器里追踪不到吧

**Comment by Kline-x** [comment]
> 可能宿主的文件变化，在容器里追踪不到吧

有办法能解决吗？大佬

**Comment by onanying** [comment]
不对，我这里也是docker，能追踪到，可能是其他问题吧

**Comment by onanying** [comment]
@914795561  找到原因了，按我这个处理 https://github.com/mix-php/swoolefor/issues/9#issuecomment-527829309

**Comment by Kline-x** [comment]
> @914795561 找到原因了，按我这个处理 [#9 (comment)](https://github.com/mix-php/swoolefor/issues/9#issuecomment-527829309)

还是不行哦，大佬

**Comment by onanying** [comment]
我测试了啊，阔以，我修改了宿主的一个文件，docker 容器里重启成功了

**Comment by onanying** [comment]
会不会是你的容器里的系统是精简版，不支持 inotify ，我容器里是 CentOS Linux release 7.3.1611 (Core)

**Comment by Kline-x** [comment]
> 会不会是你的容器里的系统是精简版，不支持 inotify ，我容器里是 CentOS Linux release 7.3.1611 (Core)

有的，我用pecl裝了个inotify，不然跑不起来

**Comment by onanying** [comment]
@914795561  我说的是 inotify 是需要操作系统支持，才能捕获到文件变更，现在是 inotify 扩展没有捕获到文件的变化，所以 swoolefor 不会重启你的命令，而在我这里是可以的，我和你的代码版本 swoolefor 1.1.2, swoole版本都是统一的 swoole 4.4.5 (根据你的描述)，只有环境是不一样，所以问题应该是环境部分

**Comment by onanying** [comment]
我的容器环境，供你参考：

```
[root@localhost data]# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.5
Built => Sep  4 2019 09:34:26
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

[root@localhost data]# php -v
PHP 7.2.12 (cli) (built: Apr  9 2019 02:42:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

[root@localhost data]# php --ri inotify 

inotify

Version => 2.0.0

[root@localhost data]# cat /etc/redhat-release                                 
CentOS Linux release 7.5.1804 (Core) 
```

**Comment by Kline-x** [comment]
我用的是alpine的环境😂😂

**Comment by onanying** [comment]
@914795561 

SwooleFor v1.1.3 已经支持文件扫描的方式捕获代码更新：

下载 swoolofor 的最新版本：https://github.com/mix-php/swoolefor/releases/latest

```
php swoolefor.phar --exec="php app.php arg..." --no-inotify
```
